services:
  arrrelay:
    build: .
    container_name: arrrelay
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3032:3032"
    volumes:
      - ./data:/data
    networks:
      - arrrelay

networks:
  arrrelay:
    name: arrrelay
